---
- name: Copy apt sources list
  copy:
    dest: '/etc/apt/sources.list'
    src: sources.list
    owner: root
    group: root
    mode: '0644'
- name: Copy apt sources preference
  copy:
    dest: '/etc/apt/preferences.d/sources_preference'
    src: sources_preference
    owner: root
    group: root
    mode: '0644'
- name: Run apt update+upgrade
  apt:
    upgrade: yes
    update_cache: yes
  register: apt_result
- name: Log changed packages
  debug:
    msg: |
      '{% for line in apt_result.stdout_lines 
      if "newly installed" in line%}
      {{ line }}
      {% endfor %}'
  when: apt_result.changed == true

- name: Specific apt packages
  apt:
    name:
      - python3-pip
      - python3-dev
      - python3-virtualenv
      - tmux
      - htop 
      - nftables
      - git
      - bgpq4
    state: latest
- name: Specific backport pacakges
  apt:
    default_release: bullseye-backports
    name:
      - bird2
    state: latest
