---
- name: Copy apt sources list
  copy:
    dest: '/etc/apt/sources.list'
    src: sources.list
    owner: root
    group: root
    mode: '0644'
- name: Copy apt sources preference
  copy:
    dest: '/etc/apt/preferences.d/sources_preference'
    src: sources_preference
    owner: root
    group: root
    mode: '0644'
- name: Install testing apt packages
  shell:
    cmd: >
      apt install -y libc-bin/testing &&
      apt install -y libc-dev-bin/testing &&
      apt install -y locales/testing &&
      apt install -y bird2/testing
- name: Update & install apt packages
  package:
    name:
      - python3-pip
      - python3-dev
      - python3-virtualenv
      - tmux
      - htop 
      - nftables
      - git
      - bgpq4
    state: latest
- name: Copy nftables config
  copy:
    dest: '/etc/nftables.conf'
    src: nftables.conf
    owner: root
    group: root
    mode: '0644'
- name: Update nftables config
  shell:
    cmd: nft -f /etc/nftables.conf
- name: Copy /etc/bird.conf
  copy:
    dest: '/etc/bird.conf'
    src: 'bird.conf'
    owner: root
    group: root
    mode: 0644
    validate: '/usr/sbin/bird -p -c %s'
  notify: reeconfigure bird
- name: Copy enp1s0 interface file
  copy:
    dest: '/etc/network/interfaces.d/enp1s0'
    src: enp1s0
    owner: root
    group: root
    mode: '0644'
- name: Reboot machine
  reboot:
