cfg:
  rs_as: 60247
  router_id: 185.0.29.1
  filtering:
    next_hop:
      policy: strict
    ipv4_pref_len:
      max: 24
      min: 8
    ipv6_pref_len:
      max: 48
      min: 12
    global_black_list_pref:
    - prefix: 185.0.29.0
      length: 24
    - prefix: '2001:7f8:149::'
      length: 48
    max_as_path_len: 32
    reject_invalid_as_in_as_path: true
    transit_free:
      action: reject
      asns:
      - 174
      - 701
      - 1299
      - 2914
      - 3257
      - 3320
      - 3356
      - 5511
      - 6453
      - 6461
      - 6762
      - 6830
      - 7018
      - 12956
    never_via_route_servers:
      peering_db: true
    irrdb:
      enforce_origin_in_as_set: true
      enforce_prefix_in_as_set: true
      allow_longer_prefixes: true
      tag_as_set: true
      peering_db: true
      use_rpki_roas_as_route_objects:
        enabled: true
      use_registrobr_bulk_whois_data:
        enabled: true
    rpki_bgp_origin_validation:
      enabled: true
      reject_invalid: true
    max_prefix:
      action: shutdown
      peering_db:
        enabled: true
    roles:
      enabled: true
    reject_policy:
      policy: tag_and_reject
  graceful_shutdown:
    enabled: true
  rfc1997_wellknown_communities:
    policy: pass
  communities:
    reject_cause:
      std: 65520:dyn_val
      ext: rt:65520:dyn_val
      lrg: rs_as:65520:dyn_val
    reject_cause_map:
      1:
        lrg: rs_as:1101:5
      2:
        lrg: rs_as:1101:3
      5:
        lrg: rs_as:1101:8
      6:
        lrg: rs_as:1101:7
      7:
        lrg: rs_as:1101:4
      8:
        lrg: rs_as:1101:14
      9:
        lrg: rs_as:1101:10
      10:
        lrg: rs_as:1101:3
      12:
        lrg: rs_as:1101:9
      14:
        lrg: rs_as:1101:13
    prefix_present_in_as_set:
      std: '64512:11'
      ext: rt:64512:11
      lrg: rs_as:64512:11
    prefix_not_present_in_as_set:
      std: '64512:10'
      ext: rt:64512:10
      lrg: rs_as:64512:10
    origin_present_in_as_set:
      std: '64512:21'
      ext: rt:64512:21
      lrg: rs_as:64512:21
    origin_not_present_in_as_set:
      std: '64512:20'
      ext: rt:64512:20
      lrg: rs_as:64512:20
    prefix_validated_via_rpki_roas:
      std: '64512:31'
      ext: rt:64512:31
      lrg: rs_as:64512:31
    route_validated_via_white_list:
      std: '64512:41'
      ext: rt:64512:41
      lrg: rs_as:64512:41
    rpki_bgp_origin_validation_not_performed:
      std: '64512:50'
      ext: rt:64512:50
      lrg: rs_as:1000:3
    rpki_bgp_origin_validation_valid:
      std: '64512:51'
      ext: rt:64512:51
      lrg: rs_as:1000:1
    rpki_bgp_origin_validation_unknown:
      std: '64512:52'
      ext: rt:64512:52
      lrg: rs_as:1000:2
    rpki_bgp_origin_validation_invalid:
      std: '64512:53'
      ext: rt:64512:53
      lrg: rs_as:1000:4
    do_not_announce_to_any:
      std: 0:rs_as
      ext: rt:0:rs_as
      lrg: rs_as:0:0
    do_not_announce_to_peer:
      std: 0:peer_as
      ext: rt:0:peer_as
      lrg: rs_as:0:peer_as
    announce_to_peer:
      std: rs_as:peer_as
      ext: rt:rs_as:peer_as
      lrg: rs_as:1:peer_as
    prepend_once_to_any:
      std: 65501:rs_as
      ext: rt:65501:rs_as
      lrg: rs_as:101:0
    prepend_twice_to_any:
      std: 65502:rs_as
      ext: rt:65502:rs_as
      lrg: rs_as:102:0
    prepend_thrice_to_any:
      std: 65503:rs_as
      ext: rt:65503:rs_as
      lrg: rs_as:103:0
    prepend_once_to_peer:
      std: 65511:peer_as
      ext: rt:65511:peer_as
      lrg: rs_as:101:peer_as
    prepend_twice_to_peer:
      std: 65512:peer_as
      ext: rt:65512:peer_as
      lrg: rs_as:102:peer_as
    prepend_thrice_to_peer:
      std: 65513:peer_as
      ext: rt:65513:peer_as
      lrg: rs_as:103:peer_as
    add_noexport_to_peer:
      std: 65281:peer_as
      ext: rt:65281:peer_as
      lrg: rs_as:65281:peer_as
    add_noadvertise_to_peer:
      std: 65282:peer_as
      ext: rt:65282:peer_as
      lrg: rs_as:65282:peer_as
